### ISSUE TITLE
Error when storing changes to encrypted file using AWS SSO and AWS profiles

### ISSUE THREAD

**Issue by w13k** [DaPutzy/intellij-sops-plugin#14]
Hey there! 

Thank you for this neat tool. I'm facing an issue with our current AWS SSO setup and saving an encrypted file back with Simple SOPS. It then says:

`Could not generate data key: [failed to encrypt new data key with master key "arn:aws:kms:xxx:xxx:key/xxx": Failed to call KMS encryption service: NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors]`

I'm storing the AWS_PROFILE within the encrypted file under

```
sops:
  kms:
    - arn: xxx
      created_at: xxx
      enc: xxx
      aws_profile: "PROFILE_NAME"
```

Maybe it's because the aws_profile gets lost on the way of re-encrypting the encrypted file? Or maybe I am missing something here? When using SOPS in the IntelliJ's terminal window, it all works.

Any help is appreciated!

Widura
